# Generated by Django 4.2.5 on 2024-12-27 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='header_image_url',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='profile_image_url',
        ),
        migrations.AddField(
            model_name='customuser',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='header_images/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
