# Generated by Django 4.2.5 on 2025-01-03 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0004_comment_retweet_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent_comment',
        ),
    ]
