# Generated by Django 4.2.5 on 2025-01-15 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0007_alter_tweet_content'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(check=models.Q(('follower', models.F('followee')), _negated=True), name='prevent_self_follow'),
        ),
    ]
